name: My Second Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Test Model
        run: echo "Test Model"

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Deploy Model
        run: echo "Deploy model to Azure"
